---
- name: Converge
  hosts: all
  gather_facts: no

  vars:
    env_user: vagrant
    env_user_home: "/home/{{ env_user }}"
    env_src: "/home/{{ env_user }}/dotfiles"

  tasks:
    - name: update and upgrade before proceeding
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes

    - name: install tools
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - vim
        - tmux
        - git
        - python-pip
        - ranger
        - ncdu
        - lnav
        - htop
      become: yes

    - name: create .vim directory
      file:
        path: "{{ env_user_home }}/.vim"
        state: directory
        owner: "{{ env_user }}"
        group: "{{ env_user }}"
        mode: 0755

#[ANSIBLE0004] Git checkouts must contain explicit version
    - name: download pathogen into .vim directory
      git:
        repo: "https://github.com/tpope/vim-pathogen.git"
        dest: "/home/{{ env_user }}/.vim/"
        clone: yes
      become: yes
      become_user: "{{ env_user }}"
      tags:
        - skip_ansible_lint

    - name: create vim bundle directory
      file:
        path: "/home/{{ env_user }}/.vim/{{ item }}"
        state: directory
        owner: "{{ env_user }}"
        group: "{{ env_user }}"
      with_items:
        - bundle

#[ANSIBLE0004] Git checkouts must contain explicit version
    - name: install vim plugins in bundle directory
      git:
        repo: "{{ item }}"
        dest: "/home/{{ env_user }}/.vim/bundle/{{ item | basename }}"
        clone: yes
        force: yes
      with_items:
        - "https://github.com/scrooloose/nerdtree"
        - "https://github.com/xuyuanp/nerdtree-git-plugin"
        - "https://github.com/pearofducks/ansible-vim"
        - "https://github.com/ekalinin/dockerfile.vim"
        - "https://github.com/bling/vim-airline"
        - "https://github.com/vim-airline/vim-airline-themes"
        - "https://github.com/tpope/vim-fugitive"
        - "https://github.com/airblade/vim-gitgutter"
        - "https://github.com/mhinz/vim-signify"
        - "https://github.com/mbbill/undotree"
        - "https://github.com/cohama/lexima.vim"
        - "https://github.com/ajh17/VimCompletesMe"
        - "https://github.com/sjl/badwolf"
        - "https://github.com/liuchengxu/space-vim-dark"
      become: yes
      become_user: "{{ env_user }}"
      tags:
        - vim-plugins
        - skip_ansible_lint

    - block:
      - name: get list of dotfiles to import
        find:
          path: "../../dotfiles"
          hidden: yes
        register: dotfiles
        delegate_to: localhost

      - name: import dotfiles
        copy:
          src: "../../dotfiles/{{ item.path | basename }}"
          dest: "{{ env_user_home }}/{{ item.path | basename }}"
          owner: "{{ env_user }}"
          group: "{{ env_user }}"
        with_items: "{{ dotfiles.files }}"

      tags:
        - vim-dotfiles

